language: python
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.34/hugo_0.34_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
script:
- hugo --buildDrafts
- mv appspec.yml public
- cp -r scripts public/
- mkdir temp
- cd public && zip -r app.zip ./*
- mv app.zip ../temp/
- cd ..
deploy:
  provider: s3
  access_key_id: AKIAIN5O72B44O5TWFVA
  secret_access_key:
    secure: ofq2WdkVFtijG9rfv4iXTGKsiPoaX1hRLxWExB3Pj8FK9dm10IqqeRbR042IKgd260HmtazVmsQ/BgQASY1QDZwmugC1WMSPx3WUxEwtOmI2Il1SL4yqz5GGJ9fCu3yJ9Y668Foh178Q10rd6C6qMUuhFASUPIo4ujXOdCZmN4rzwq7GK9XgRbdNvNSgXmuUbSPI5zhnVvShJJDtJgR+VCh5QXdb8Vokb0BxnaooRgHgh7JtjgT7hs31TAXZ8LmmJfXc7XFePKt8WShbNa2O2M8vyE7sFwRsMiGTNTYLO/5wo0QT/1l1Q6CdDjyiS3DUOldS1y2mbOaAgSvL9oCemMx2UYD4ucPXNekeFRrKI86jBEjKGFnOspqL8Cx5us7181JxBZW1zVoj7p2tsfzQXnvkZ7SUQ86+99sPxA4kejWl5Wlfli2aBVjx9jCxC0UO7ii97FXbPDQKSAIEk/LyRc1Rh1EKeaHt0BK+6+WNeuQNtbF+hlFDXIKX6Gsly61hZpZF1Sdt/oFehVO5hHB+jPEL4IYGt8N2rsoSoJtzVsH2lafxsFZrS0/rf4n/iAmw/hK0NJ+S1U/5YfjfEQopWBN3mUv9ACzFeSkDT6FUHkWAwbuqJSEuXiuHY3gU6UmLWK+GkQKWxfM2lnQbOJDczg0KScOi1/O8qLJrcNV1RzE=
  bucket: tutorialedge.net
  local-dir: temp
  acl: public_read
  on:
    repo: elliotforbes/tutorialedge-v2
